// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings()
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusQueueActiveMessagesDataPoint(ts, 1, "queue-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusQueueCurrentSizeDataPoint(ts, 1, "queue-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusQueueDeadletterMessagesDataPoint(ts, 1, "queue-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusQueueMaxSizeDataPoint(ts, 1, "queue-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusQueueScheduledMessagesDataPoint(ts, 1, "queue-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusTopicCurrentSizeDataPoint(ts, 1, "topic-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusTopicMaxSizeDataPoint(ts, 1, "topic-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusTopicScheduledMessagesDataPoint(ts, 1, "topic-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusTopicSubscriptionActiveMessagesDataPoint(ts, 1, "topic-val", "subscription-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordServicebusTopicSubscriptionDeadletterMessagesDataPoint(ts, 1, "topic-val", "subscription-val")

			rb := mb.NewResourceBuilder()
			rb.SetServicebusNamespaceName("servicebus.namespace.name-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "servicebus.queue.active_messages":
					assert.False(t, validatedMetrics["servicebus.queue.active_messages"], "Found a duplicate in the metrics slice: servicebus.queue.active_messages")
					validatedMetrics["servicebus.queue.active_messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The number of active messages on the Service Bus queue", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("queue")
					assert.True(t, ok)
					assert.EqualValues(t, "queue-val", attrVal.Str())
				case "servicebus.queue.current_size":
					assert.False(t, validatedMetrics["servicebus.queue.current_size"], "Found a duplicate in the metrics slice: servicebus.queue.current_size")
					validatedMetrics["servicebus.queue.current_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The current size of the Service Bus queue in bytes", ms.At(i).Description())
					assert.Equal(t, "{bytes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("queue")
					assert.True(t, ok)
					assert.EqualValues(t, "queue-val", attrVal.Str())
				case "servicebus.queue.deadletter_messages":
					assert.False(t, validatedMetrics["servicebus.queue.deadletter_messages"], "Found a duplicate in the metrics slice: servicebus.queue.deadletter_messages")
					validatedMetrics["servicebus.queue.deadletter_messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The number of deadletter messages on the Service Bus queue", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("queue")
					assert.True(t, ok)
					assert.EqualValues(t, "queue-val", attrVal.Str())
				case "servicebus.queue.max_size":
					assert.False(t, validatedMetrics["servicebus.queue.max_size"], "Found a duplicate in the metrics slice: servicebus.queue.max_size")
					validatedMetrics["servicebus.queue.max_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The max size of the Service Bus queue in bytes", ms.At(i).Description())
					assert.Equal(t, "{bytes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("queue")
					assert.True(t, ok)
					assert.EqualValues(t, "queue-val", attrVal.Str())
				case "servicebus.queue.scheduled_messages":
					assert.False(t, validatedMetrics["servicebus.queue.scheduled_messages"], "Found a duplicate in the metrics slice: servicebus.queue.scheduled_messages")
					validatedMetrics["servicebus.queue.scheduled_messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The number of scheduled messages on the Service Bus queue", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("queue")
					assert.True(t, ok)
					assert.EqualValues(t, "queue-val", attrVal.Str())
				case "servicebus.topic.current_size":
					assert.False(t, validatedMetrics["servicebus.topic.current_size"], "Found a duplicate in the metrics slice: servicebus.topic.current_size")
					validatedMetrics["servicebus.topic.current_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The current size of the Service Bus topic in bytes", ms.At(i).Description())
					assert.Equal(t, "{bytes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("topic")
					assert.True(t, ok)
					assert.EqualValues(t, "topic-val", attrVal.Str())
				case "servicebus.topic.max_size":
					assert.False(t, validatedMetrics["servicebus.topic.max_size"], "Found a duplicate in the metrics slice: servicebus.topic.max_size")
					validatedMetrics["servicebus.topic.max_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The max size of the Service Bus topic in bytes", ms.At(i).Description())
					assert.Equal(t, "{bytes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("topic")
					assert.True(t, ok)
					assert.EqualValues(t, "topic-val", attrVal.Str())
				case "servicebus.topic.scheduled_messages":
					assert.False(t, validatedMetrics["servicebus.topic.scheduled_messages"], "Found a duplicate in the metrics slice: servicebus.topic.scheduled_messages")
					validatedMetrics["servicebus.topic.scheduled_messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The number of scheduled messages on the Service Bus topic", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("topic")
					assert.True(t, ok)
					assert.EqualValues(t, "topic-val", attrVal.Str())
				case "servicebus.topic.subscription.active_messages":
					assert.False(t, validatedMetrics["servicebus.topic.subscription.active_messages"], "Found a duplicate in the metrics slice: servicebus.topic.subscription.active_messages")
					validatedMetrics["servicebus.topic.subscription.active_messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The number of active messages on the Service Bus topic subscription", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("topic")
					assert.True(t, ok)
					assert.EqualValues(t, "topic-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("subscription")
					assert.True(t, ok)
					assert.EqualValues(t, "subscription-val", attrVal.Str())
				case "servicebus.topic.subscription.deadletter_messages":
					assert.False(t, validatedMetrics["servicebus.topic.subscription.deadletter_messages"], "Found a duplicate in the metrics slice: servicebus.topic.subscription.deadletter_messages")
					validatedMetrics["servicebus.topic.subscription.deadletter_messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "The number of deadletter messages on the Service Bus topic subscription", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("topic")
					assert.True(t, ok)
					assert.EqualValues(t, "topic-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("subscription")
					assert.True(t, ok)
					assert.EqualValues(t, "subscription-val", attrVal.Str())
				}
			}
		})
	}
}
