dist:
  name: azureservicebus-otel-collector
  description: Azure Service Bus custom collector
  output_path: ./collector
  version: 0.0.1
#  debug_compilation: true

receivers:
  - gomod: github.com/Integrio/azureservicebusreceiver v1.0.0
    name: azureservicebusreceiver

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.121.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.121.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.121.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.121.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.121.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.19.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0

replaces:
  - github.com/Integrio/azureservicebusreceiver => ../